---
abstract: 'automatically delete empty keys from query parameters'
author:
  - 'Zoffix Znet <cpan@zoffix.com>'
build_requires:
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.012, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: App-ZofCMS-Plugin-AutoEmptyQueryDelete
requires:
  strict: 0
  warnings: 0
resources:
  bugtracker: https://github.com/zoffixznet/App-ZofCMS-Plugin-AutoEmptyQueryDelete/issues
  repository: git://github.com/zoffixznet/App-ZofCMS-Plugin-AutoEmptyQueryDelete.git
version: 1.001001
