---
name: App-ZofCMS-Plugin-AutoEmptyQueryDelete
version: 0.0101
author:
  - "'Zoffix <'zoffix@cpan.org'>"
abstract: automatically delete empty keys from query parameters
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  Test::More: 0
provides:
  App::ZofCMS::Plugin::AutoEmptyQueryDelete:
    file: lib/App/ZofCMS/Plugin/AutoEmptyQueryDelete.pm
    version: 0.0101
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
